### ISSUE TITLE
primCasePair question

### ISSUE THREAD

**Issue by iomeone** [Ailrun/core-lang-haskell#6]
https://github.com/Ailrun/core-lang-haskell/blob/f6f700ad08fe31bd765381b7e18b747ff2f07c44/src/Language/TiMachine.hs#L1178

this line of code is correct, but I think it's better to write it as :
`| otherwise -> ([exprAddr],  stack : dump, heap, globals, stats)`

How do you think of it？

**Comment by iomeone** [comment]
compare these two picture drawn by code  `main = snd (MkPair 2 4);`
https://raw.githubusercontent.com/iomeone/graphReduction/master/png/snd_MkPair.png
this picture is using my suggested code.

https://raw.githubusercontent.com/iomeone/graphReduction/master/png/snd_MkPair_2.png
this picture is using your code.

the Tree before step10 is the same.
the key difference is step 11.   
if adopt your code to draw the tree,  the primitive casePair node will step again, which I think 
don't need to.

**Comment by Ailrun** [comment]
@iomeone See the _chapter 2.6.1_ of [the book](https://github.com/Ailrun/core-lang-haskell#reference-1).
You can notice that if you don't unroll the stack, you cannot execute following program (or any other program that makes `NInd` node in the place of the first argument of `casePair`).
```
f x = if (x > 3) (MkPair 3 3) (MkPair 5 5); main = snd (f 4)
```
Same technique is applied to other `prim`- functions too.

**Comment by iomeone** [comment]
Yes，from your method of  implementation of primCasePair, your explaination is make sense.
https://github.com/Ailrun/core-lang-haskell/blob/f6f700ad08fe31bd765381b7e18b747ff2f07c44/src/Language/TiMachine.hs#L1174
if expr is not NData 1 [arg1, arg2] and also not DataNode, you begin to compute the expr.
So the NInd expr will compute again and again, and finally cause infinite loop.

but my implementaion of primCasePair's case expression use
https://github.com/iomeone/graphReduction/blob/019c952305a7d691c5a73b47b81c054bca62c784/src/Eval.hs#L195

```
isPairNodeEx :: TiHeap-> Addr -> Bool
isPairNodeEx heap pairAddr =   
    case (hLookup heap pairAddr) of
        (NData 2 [_, _])        -> True
        NInd addrind            -> isPairNodeEx heap addrind
        _                       ->False

```


So both of our implemention is make sense, but adopt difference approch !

**Comment by iomeone** [comment]
but I still don't understand why you can get rid of the  infinite loop ...
your caseApStack 's argument will always an NInd node.
Where do you update the NInd Node to the NData node?

**Comment by iomeone** [comment]
oh, I see. 
```
apStep (stack@(topAddr : _), dump, heap, globals, stats) a1 a2
  = case arg of
      NInd a3 -> (stack, dump, makeHeap a3, globals, stats)
      _ -> (a1 : stack, dump, heap, globals, stats)
  where
    makeHeap = statHUpdate heap topAddr . NAp a1
    arg = statHLookup heap a2
```
when you unroll your stack, in next computation round ,  you excute the apStep again, and elimate the NInd Node.

`NInd a3 -> (stack, dump, makeHeap a3, globals, stats)` is the key!!!!

**Comment by Ailrun** [comment]
The problem(?) of your implementation is now your 'primitive' step is quite heavy. When you have `NInd (NInd (NInd ... (NData 2 _ _) ... ))` with n `NInd`s, your primitive will follow these n `NInd`s in one step, i.e., access the heap more than `n+1` times in a single step. That makes your primitive step really heavy, and counteracts the fundamental reason (= constructing and expressing graphs in light, simple, and linearized steps) we compile our codes.

**Comment by Ailrun** [comment]
Of course you can follow indirection one by one per a step in `prim`- functions, and that could save one step for your original case.
However, to do that, you need to implement "following indirection one by one per a step" functionality for every `prim`- functions that requires evaluation of child node, and that could be complex (in terms of code size).

**Comment by iomeone** [comment]
yes, you are right , it's not efficient 
`pairApply heap (NInd addrind) f   =   pairApply heap (hLookup heap addrind) f`
this code will  access the heap again and again which your method do not need to.

and also make the code complex (need  implement NInd case in every prim step and also casepair step). 

OK, thank you for the nice reply ! And I think I understand the problem totally.

**Comment by Ailrun** [comment]
My pleasure! I'm glad you think so. Have a happy coding day :)
